#!/bin/bash

echo "🔍 Cloudflare D1 Token Setup Guide"
echo "=================================="
echo ""
echo "Step 1: Get your Cloudflare Account ID"
echo "---------------------------------------"
echo "Run this command to see your account details:"
echo ""
echo "npx wrangler whoami"
echo ""
read -p "Press Enter to continue..."

npx wrangler whoami

echo ""
echo "Step 2: Create a new API Token"
echo "-------------------------------"
echo "1. Go to: https://dash.cloudflare.com/profile/api-tokens"
echo "2. Click 'Create Token'"
echo "3. Use 'Custom token' template"
echo "4. Configure as follows:"
echo ""
echo "   Token name: GitHub Actions D1 Scraper"
echo ""
echo "   Permissions:"
echo "   - Account > D1 > Edit"
echo "   - Account > Cloudflare Workers > Edit (optional)"
echo ""
echo "   Account Resources:"
echo "   - Include > Your Account (shown above)"
echo ""
echo "   Zone Resources:"
echo "   - Include > All zones (or specific zone if you have one)"
echo ""
echo "5. Click 'Continue to summary'"
echo "6. Click 'Create Token'"
echo "7. COPY THE TOKEN (you won't see it again!)"
echo ""
echo "Step 3: Test the token locally"
echo "-------------------------------"
echo "Export the token and test it:"
echo ""
echo "export CLOUDFLARE_API_TOKEN='your-token-here'"
echo "npx wrangler d1 execute Calhr --remote --command \"SELECT COUNT(*) FROM ccJobs\" --json"
echo ""
echo "Step 4: Add to GitHub Secrets"
echo "------------------------------"
echo "1. Go to: https://github.com/bhope78/scraper/settings/secrets/actions"
echo "2. Click on CLOUDFLARE_API_TOKEN"
echo "3. Click 'Update'"
echo "4. Paste the token (no quotes, no spaces)"
echo "5. Click 'Update secret'"
echo ""
echo "✅ Once done, the workflow should work!"